--- 
title: "COVID Visualization Project"
author: "Andy Cho, Ardus Kong, Xuanhao Wu"
date: "2020-12-17"
site: bookdown::bookdown_site
github-repo: andycho97/COVID_Visualization_Project
description: "This project is by Andy, Andus, and Xuanhao"
---

# Introduction

COVID-19 Pandemic is easily one of the top few words that come up when discussing the year 2020. In the United States, the first case was found in Snohomish, Washington on January 21, 2020. It was not until March that the federal government officially declared a state of emergency and the cases started to rise exponentially. Against the optimistic belief that COVID-19 cases will reduce significantly in the summer, the number of cases in the United States showed a modest decrease in late spring, followed by a second wave in the summer, and a third wave in late 2020.

Our group wanted to further explore the COVID-19 patterns in the United States, specifically on the state level. Different states had vastly differeing approaches to the pandemic and we were curious to answer these questions:

- What are some major COVID-19 patterns (cases and deaths) in the US, in relation to major domestic events?

- What are some major COVID-19 Patterns (cases and deaths) when stratified by states/regions, and if necessary, specific counties of the state?

- What are some patterns that can signal a major upcoming wave? (e.g. if we see a steady growth in cases/deaths for x consecutive days, does that tell us a bigger picture about the state of COVID-19 in the US or a specific state?)

We came up with visualizations that help answer the questions above. Explore each sections on the left-hand side of your screen!